const U1 = {
  name: "U1",
  stations: [
    { name: "Warschauer Str.", imoji: "🎉💃🔥" },
    { name: "Schlesisches Tor", imoji: "🚬🍁🍀" },
    { name: "Görlitzer Bahnhof" },
    { name: "Kottbusser Tor" },
  ],
};

const U2 = {
  name: "U2",
  stations: [
    { name: "Ruhleben" },
    { name: "Olympia-Stadion", imoji: "🏟️🏐🎪" },
    { name: "Neu-Westend" },
    { name: "Theodor-Heuss-Platz" },
    { name: "Kaiserdamm" },
    { name: "Sophie-Charlotte-Platz -", imoji: "🏰" },
    { name: "Bismarckstraße", imoji: "🤴👴🏻" },
    { name: "Deutsche Oper", imoji: "🎷👩‍🎤🎺" },
    { name: "Ernst-Reuter-Platz" },
    { name: "Zoologischer Garten", imoji: "🐻🐍🐒" },
    { name: "Wittenbergplatz" },
    { name: "Nollendorfplatz" },
    { name: "Bülowstraße" },
    { name: "Gleisdreieck" },
    { name: "Mendelssohn-Bartholdy-Park" },
    { name: "Potsdamer Platz", imoji: "🎦" },
    { name: "Mohrenstraße", imoji: "🛍️" },
    { name: "Stadtmitte" },
    { name: "Hausvogteiplatz" },
    { name: "Spittelmarkt" },
    { name: "Märkisches Museum", imoji: "🎨🏛️🧑‍🎨" },
    { name: "Klosterstraße" },
    { name: "Alexanderplatz", imoji: "🗼💈🛍️" },
    { name: "Rosa-Luxemburg-Platz" },
    { name: "Senefelderplatz" },
    { name: "Eberswalder Straße" },
    { name: "Schönhauser Allee" },
    { name: "Vinetastraße" },
    { name: "Pankow" },
  ],
};

const U3 = {
  name: "U3",
  stations: [
    { name: "Krumme Lanke", imoji: "🌞🌊🏖️" },
    { name: "Onkel Toms Hütte", imoji: "🤠👨🏻‍🌾" },
    { name: "Oskar-Helene-Heim" },
    { name: "Freie Universität (Thielplatz)", imoji: "🎓📒" },
    { name: "Dahlem-Dorf" },
    { name: "Podbielskiallee" },
    { name: "Breitenbachplatz" },
    { name: "Rüdesheimer Platz" },
    { name: "Heidelberger Platz" },
    { name: "Fehrbelliner Platz" },
    { name: "Hohenzollernplatz" },
    { name: "Spichernstr." },
    { name: "Augsburger Str." },
    { name: "Wittenbergplatz" },
    { name: "Nollendorfplatz" },
    { name: "Kurfürstenstr." },
    { name: "Gleisdreieck" },
    { name: "Möckernbrücke" },
    { name: "Hallesches Tor" },
    { name: "Prinzenstraße", imoji: "🤴👑" },
    { name: "Kottbusser Tor" },
  ],
};

const U4 = {
  name: "U4",
  stations: [
    { name: "Innsbrucker Platz" },
    { name: "Rathaus Schöneberg" },
    { name: "Bayerischer Platz", imoji: "🍺" },
    { name: "Viktoria-Luise-Platz" },
    { name: "Nollendorfplatz" },
  ],
};

const U5 = {
  name: "U5",
  stations: [
    { name: "Hünow" },
    { name: "Louis-Lewin-Str." },
    { name: "Hellersdorf" },
    { name: "Cottbusser Platz" },
    { name: "Kienberg (Gärten Der Welt)", imoji: "🏡☘️🌴" },
    { name: "Kaulsdorf-Nord" },
    { name: "Wuhletal" },
    { name: "Elsterwerdaer Platz" },
    { name: "Biesdorf-Süd" },
    { name: "Tierpark", imoji: "🏞🐨" },
    { name: "Friedrichsfelde" },
    { name: "Lichtenberg" },
    { name: "Magdalenenstr." },
    { name: "Frankfurter Allee" },
    { name: "Samariterstr." },
    { name: "Frankfurter Tor" },
    { name: "Weberwiese" },
    { name: "Strausberger Platz" },
    { name: "Schillingstraße" },
    { name: "Alexanderplatz", imoji: "🗼💈🛍️" },
  ],
};

const U6 = {
  name: "U6",
  stations: [
    { name: "Alt-Tegel" },
    { name: "Borsigwerke" },
    { name: "Holzhauser Str." },
    { name: "Otisstr." },
    { name: "Scharnweberstr." },
    { name: "Kurt-Schumacher-Platz" },
    { name: "Afrikanische Str." },
    { name: "Rehberge" },
    { name: "Seestraße" },
    { name: "Leopoldplatz" },
    { name: "Wedding" },
    { name: "Reinickendorfer Str." },
    { name: "Schwartzkopffstr." },
    { name: "Naturkundemuseum", imoji: "🏛️🖼️🌳" },
    { name: "Oranienburger Tor" },
    { name: "Friedrichstr. Bhf" },
    { name: "Französische Str.", imoji: "🇫🇷👨‍🎨" },
    { name: "Stadtmitte" },
    { name: "Checkpoint Charlie", imoji: "🇺🇸💂🇷🇺" },
    { name: "Hallesches Tor" },
    { name: "Mehringdamm", imoji: "🥙" },
    { name: "Paradestr." },
    { name: "Tempelhof" },
    { name: "Alt-Tempelhof" },
    { name: "Kaiserin-Augusta-Str." },
    { name: "Ullsteinstr." },
    { name: "Westphalweg" },
    { name: "Alt-Mariendorf" },
  ],
};

const U7 = {
  name: "U7",
  stations: [
    { name: "Rathaus Spandau" },
    { name: "Altstadt Spandau" },
    { name: "Zitadelle" },
    { name: "Haselhorst" },
    { name: "Paulsternstr." },
    { name: "Rohrdamm" },
    { name: "Siemensdamm" },
    { name: "Halemweg" },
    { name: "Jakob-Kaiser-Platz" },
    { name: "Jungfernheide Bhf" },
    { name: "Mierendorffplatz" },
    { name: "Richard-Wagner-Platz" },
    { name: "Bismarckstraße" },
    { name: "Wilmersdorfer Str." },
    { name: "Adenauerplatz" },
    { name: "Konstanzer Str." },
    { name: "Fehrbelliner Platz" },
    { name: "Blissestr." },
    { name: "Bayerischer Platz", imoji: "🍺" },
    { name: "Eisenacher Str." },
    { name: "Kleistpark" },
    { name: "Yorckstraße" },
    { name: "Möckernbrücke" },
    { name: "Mehringdamm", imoji: "🥙" },
    { name: "Gneisenaustr." },
    { name: "Südstern" },
    { name: "Hermannplatz" },
    { name: "Rathaus Neukölln" },
    { name: "Karl-Marx-Str.", imoji: "🧠🤔💭" },
    { name: "Neukölln", imoji: "😎" },
    { name: "Grenzallee" },
    { name: "Blaschkoallee" },
    { name: "Parchimer Allee" },
    { name: "Britz-Süd" },
  ],
};

const U8 = {
  name: "U8",
  stations: [
    { name: "Hermannstr." },
    { name: "Leinestr." },
    { name: "Boddinstr." },
    { name: "Hermannplatz" },
    { name: "Schönleinstr." },
    { name: "Kottbusser Tor" },
    { name: "Moritzplatz" },
    { name: "Heinrich-Heine-Str." },
    { name: "Jannowitzbrücke" },
    { name: "Alexanderplatz", imoji: "🗼💈🛍️" },
    { name: "Weinmeisterstr." },
    { name: "Rosenthaler Platz" },
    { name: "Bernauer Str." },
    { name: "Voltastr." },
    { name: "Gesundbrunnen Bhf" },
    { name: "Pankstraße" },
    { name: "Osloer Str.", imoji: "🇳🇴" },
    { name: "Franz-Neumann-Platz" },
    { name: "Residenzstraße" },
    { name: "Paracelsus-Bad" },
    { name: "Lindauer Allee" },
    { name: "Karl-Bonhoeffer-Nervenklinik" },
    { name: "Rathaus Reinickendorf" },
    { name: "Wittenau" },
  ],
};

const U9 = {
  name: "U9",
  stations: [
    { name: "Rathaus Steglitz" },
    { name: "Schloßstr." },
    { name: "Walther-Schreiber-Platz" },
    { name: "Friedrich-Wilhelm-Platz" },
    { name: "Bundesplatz" },
    { name: "Güntzelstr." },
    { name: "Spichernstr." },
    { name: "Kurfürstendamm" },
    { name: "Zoologischer Garten", imoji: "🐻🐍🐒" },
    { name: "Hansaplatz", imoji: "🗿🗽🧚‍♀️" },
    { name: "Turmstraße" },
    { name: "Birkenstr." },
    { name: "Westhafen" },
    { name: "Amrumer Str." },
    { name: "Leopoldplatz" },
    { name: "Nauener Platz" },
    { name: "Osloer Str.", imoji: "🇳🇴" },
  ],
};

module.exports = {
  allLines: {
    U1,
    U2,
    U3,
    U4,
    U5,
    U6,
    U7,
    U8,
    U9,
  },
  gitRemoteHead: "git@github.com:ayonious/git-network-trainline.git",
};
